# Generated by Django 4.0.2 on 2022-02-23 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crud',
            old_name='published',
            new_name='completed',
        ),
    ]
